### ISSUE TITLE
App crashing on selection of invalid url

### ISSUE THREAD

**Issue by CampbellMG** [bernaferrari/ChangeDetection#12]
Hi, 

I just stumbled across this app through Reddit and found a bug you may want to be aware of:

The app crashes with the following dump if you select a list item with an invalid URL.

```
06-20 15:13:35.459 16265-16265/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bernaferrari.changedetection, PID: 16265
    kotlin.KotlinNullPointerException
        at com.bernaferrari.changedetection.MainFragment$updateBottomSheet$1$1.doResume(MainFragment.kt:174)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:26)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6642)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by bernaferrari** [comment]
Thanks! I just figured out what was happening and fixed already!

https://github.com/bernaferrari/ChangeDetection/commit/baec92ea16c38c2129084999170b5b332f4652c8
