### ISSUE TITLE
Aplication Force Close After Click Background Sync

### ISSUE THREAD

**Issue by tri-evendi** [bernaferrari/ChangeDetection#36]
2019-11-30 08:10:29.916 25008-25008/com.bernaferrari.changedetection D/Dialog: mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
2019-11-30 08:10:30.027 25008-25027/com.bernaferrari.changedetection I/changedetectio: Background concurrent copying GC freed 60355(2MB) AllocSpace objects, 10(388KB) LOS objects, 49% free, 4MB/9MB, paused 5.492ms total 129.482ms
2019-11-30 08:10:30.113 25008-25008/com.bernaferrari.changedetection I/DecorView: mWindow.mActivityCurrentConfig is null.
2019-11-30 08:10:30.115 25008-25008/com.bernaferrari.changedetection I/DecorView: createDecorCaptionView >> DecorView@e0a5891[], isFloating: true, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: false
2019-11-30 08:10:30.334 25008-25008/com.bernaferrari.changedetection D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2019-11-30 08:10:30.338 25008-25008/com.bernaferrari.changedetection E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bernaferrari.changedetection, PID: 25008
    java.lang.IllegalStateException: kindPicker must not be null
        at com.bernaferrari.changedetection.settings.DialogBackgroundSync.setUpViews(DialogBackgroundSync.kt:45)
        at com.bernaferrari.changedetection.settings.DialogBackgroundSync.onCreateDialog(DialogBackgroundSync.kt:36)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:380)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1403)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2076)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1821)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7081)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by tri-evendi** [comment]
running in version 2.3. it's new? aplication force close after click background sync option
