### ISSUE TITLE
Find some crashes!

### ISSUE THREAD

**Issue by LvZW1895** [bernaferrari/ChangeDetection#49]
APK Version : 2.3
AndroidOS Version = 6.0-9.0
**Description information：**
These crashes happened by accident when I was testing in different devices. I tried to reproduce them and found that they can't be reproduced, but they are real. I hope they can help you to debug.

**Crash 1:**
Long Msg: java.lang.IllegalStateException: kindPicker must not be null
	at com.bernaferrari.changedetection.settings.DialogBackgroundSync.setUpViews(DialogBackgroundSync.kt:45)
	at com.bernaferrari.changedetection.settings.DialogBackgroundSync.onCreateDialog(DialogBackgroundSync.kt:36)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:403)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1484)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Crash 2:**
Long Msg: com.airbnb.epoxy.ImmutableModelException: The model was changed between being bound and when models were rebuilt Position: 6 Model: ColorPickerItemEpoxy_{switchIsOn=true, gradientColor=(-282565, -2878374), allowDeselection=false}ColorPickerItemEpoxy_{id=-4391967760750466383, viewType=2131558439, shown=true, addedToAdapter=false}

Epoxy attribute fields on a model cannot be changed once the model is added to a controller. Check that these fields are not updated, or that the assigned objects are not mutated, outside of the buildModels method. The only exception is if the change is made inside an Interceptor callback. Consider using an interceptor if you need to change a model after it is added to the controller and before it is set on the adapter. If the model is already set on the adapter then you must call `requestModelBuild` instead to recreate all models.
	at com.airbnb.epoxy.EpoxyModel.validateStateHasNotChangedSinceAdded(EpoxyModel.java:466)
	at com.airbnb.epoxy.EpoxyControllerAdapter.setModels(EpoxyControllerAdapter.java:67)
	at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:294)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by rishujam** [comment]
Hey, Is this project still being maintained

**Comment by bernaferrari** [comment]
Good question. The answer is probably no. I spent 4 frustrating hours yesterday trying to compile for target 33 with no success (but aaalmost!). When I was developing I stopped because Android view was too bad, and now there is Compose which is great, but I need to rewrite everything, so that's too time consuming. I'm still thinking what I should do with this app. Any ideas?

**Comment by rishujam** [comment]
It would be great if it continues.

**Comment by bernaferrari** [comment]
Yeah, but lol I would need to charge money, what would make you pay for it?

**Comment by dktzde** [comment]
@bernaferrari Perhaps the question is also how much money you need for this. I just looked, but I didn't find you on GitHub Sponsor or LiberaPay.
